### ISSUE TITLE
ERR_INVALID_CALLBACK

### ISSUE THREAD

**Issue by jsepia** [entozoon/readme-kanban-board#1]
## Test case

**README.md**

```md
<!---KANBAN
# To scan

- Barn owl
- Art trade tiger sketch
- The Moon

# To upload/format/reformat

- Existing tarot cards

# Done

- Nothing
KANBAN--->
```

## Error

```
$ npm run readme-kanban-board

> mypackage@2.0.0 readme-kanban-board /myproject
> readme-kanban-board

 -- Readme Kanban Board --
./README.md
# To scan

- Barn owl
- Art trade tiger sketch
- The Moon

# To upload/format/reformat

- Existing tarot cards

# Done

- Nothing
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1179:14)
    at err (/myproject/node_modules/readme-kanban-board/bin/readme-kanban-board.js:121:14)
    at ChildProcess.<anonymous> (/myproject/node_modules/webshot/lib/webshot.js:248:9)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

## Node and NPM versions

```
$ node -v
v11.12.0
$ npm -v
6.7.0
```

## Other debugging info

I'm running this on Debian, but through the Linux Subsystem for Windows.

**Comment by entozoon** [comment]
https://github.com/entozoon/readme-kanban-board/pull/2
